### ISSUE TITLE
Unable to rebuild/update playground.

### ISSUE THREAD

**Issue by shurcooL** [gopherjs/gopherjs.github.io#27]
If I'm not mistaken, it seems the playground is in a broken state if one tries to rebuild it. I suspect it's a result of changing importer/exporter in https://github.com/gopherjs/gopherjs/commit/d60db54d81979234899c62702870360fd84ac03c.

When I rebuild/update the playground using the latest version of GopherJS, I get `Uncaught Error: AddInt32 already declared` panics when the playground loads.

I was able to get around that temporarily by making the following change to `golang.org/x/tools/go/importer` package, `importer.go` file:

```Go
if alt := pkg.Scope().Insert(obj); alt != nil {
	//panic(fmt.Sprintf("%s already declared", alt.Name()))
	println(fmt.Sprintf("%s already declared", alt.Name()))
}
```

That way the playground seems to work, but it does print the above warning quite a few times, seemingly for all exported symbols in `sync/atomic` and `unicode` packages (no idea why those specifically).

It is possible I messed something up with the `update.sh` script since I had to do its steps manually (since my GOROOT is not user-writeable, I have multiple GOPATH workspaces, etc.), but I double checked very carefully so the chance is quite low. I think it's a legitimate issue. I wasn't able to investigate it much further because I'm not very familiar with `golang.org/x/tools/go/importer` package at this time.

**Comment by neelance** [comment]
`update.sh` works fine for me (except the two paths that you mentioned and which are fixed now). What might be different between our setups?

**Comment by shurcooL** [comment]
> `update.sh` works fine for me (except the two paths that you mentioned and which are fixed now).

Have you tested the Playground?

I'm using latest stable Chrome on OS X and it gives me the error I mentioned earlier on load:

![image](https://cloud.githubusercontent.com/assets/1924134/7909109/c3d879e8-07fe-11e5-8b65-1bf45ca16ed6.png)

If I click Run, it gives another error `ASCII_Hex_Digit already declared` and nothing happens. If I click Run a second time, it seems to execute the snippet code okay.

**Comment by neelance** [comment]
Oh right, I just clicked on "Run" and it seemed to work. I did not check the JS console. Thx for making me aware.

**Comment by shurcooL** [comment]
Any updates on what the issue could be?

I've tried it again just now, and with the latest packages for everything, the issue still persists and I'm unable to rebuild the playground without it panicking in the console.

![image](https://cloud.githubusercontent.com/assets/1924134/8398491/00ee9964-1da5-11e5-9cfd-48993a5b467e.png)

> I was able to get around that temporarily by making the following change to `golang.org/x/tools/go/importer` package, `importer.go` file:
> 
> ```Go
> if alt := pkg.Scope().Insert(obj); alt != nil {
> 	//panic(fmt.Sprintf("%s already declared", alt.Name()))
> 	println(fmt.Sprintf("%s already declared", alt.Name()))
> }
> ```
> 
> That way the playground seems to work, but it does print the above warning quite a few times, seemingly for all exported symbols in `sync/atomic` and `unicode` packages (no idea why those specifically).

Any ideas why `sync/atomic` and `unicode` packages specifically are getting duplicate symbols?

**Comment by shurcooL** [comment]
It seems this issue is not completely resolved. See https://github.com/gopherjs/gopherjs.github.io/issues/34.
